baseurl = "http://ofjamescole.com.s3-website-us-east-1.amazonaws.com/"
languageCode = "en-us"
title = "James Cole"
pygmentsstyle = "friendly"
disqusShortname = "jamescole"
SectionPagesMenu = "main"

[params]
  githubName = "tortillaj"
  twitterName = "jemilco"
  facebookName = ""
  linkedinName = ""
  instagramName = ""
  dribbbleName = ""
  cover = "img/philly.png"
  author = "James Cole"
  bio = "Web Developer"
  authorimage = "img/self.jpg"
  authorlocation = "BTV // PHL // AUS // ABQ"
  authorwebsite = "http://ofjamescole.com"
