baseurl = "http://ofjamescole.com.s3-website-us-east-1.amazonaws.com/"
languageCode = "en-us"
title = "My New Hugo Site"
pygmentsstyle = "friendly"
disqusShortname = "jamescole"
SectionPagesMenu = "main"

[params]
  githubName = "tortillaj"
  twitterName = "jemilco"
  facebookName = ""
  linkedinName = ""
  instagramName = ""
  dribbbleName = ""
  cover = "img/philly.png"

