name = "Flatline"
license = "MIT"
licenselink = "https://github.com/vjeantet/hugo-theme-casper/blob/master/LICENSE.md"
description = "Flatline Theme for Hugo"
homepage = "http://vjeantet.fr/"
tags = ["blog"]
features = ["gulp", "disqus", "google analytics", "share"]
min_version=0.14

[author]
  name = "James Cole"
  homepage = "http://ofjamescole.com"

